### ISSUE TITLE
Collapse sometimes doesn't work

### ISSUE THREAD

**Issue by underdoeg** [urre/acf-fold-flexible#2]
When clicking on the header area, sometimes the field doesn't hide its content. The header gets gray and a plus icon appears though.

![selection_162](https://cloud.githubusercontent.com/assets/243820/5327806/2b6db064-7d62-11e4-98b0-1b8d304ee04e.png)

**Comment by urre** [comment]
what version of ACF is this? @underdoeg

**Comment by underdoeg** [comment]
The recent acf pro

**Comment by urre** [comment]
Ok. Has the post you are editing been saved/published?

**Comment by underdoeg** [comment]
sorry, I can't tell any more. But it is possible that it has not yet been saved...

**Comment by urre** [comment]
Ok. Save/update and this should work. Otherwise, get back
