### ISSUE TITLE
Possible to embed into plugin lie ACF allows?

### ISSUE THREAD

**Issue by cmwwebfx** [urre/acf-fold-flexible#3]
If so, how can I do this please.

**Comment by urre** [comment]
how do you mean? @cmwwebfx

**Comment by cmwwebfx** [comment]
Sorry for the typo.
ACF has a way to embed ACF into a custom plugin that I will build. How will this embed into a plugin other than installing as a separate plugin.

**Comment by urre** [comment]
Ah, this was just mean as separate addon. So don't know if that's possible right now. Have to look in to that.
