### ISSUE TITLE
Correct styling for newly added items

### ISSUE THREAD

**Issue by jnicol** [urre/acf-fold-flexible#4]
I don't have time to do a pull request, but I notice that the "open" class is not correctly added/removed from newly added fields when they are collapsed/expanded. (i.e. they always stay blue)

This could be fixed by passing a selector to `on()` at line 96 of `acf-fold-flexible.admin.js`:

    $('.acf-postbox').on('click', '.acf-fc-layout-handle', function() {

**Comment by urre** [comment]
@jnicol thanks! also fixed so newly added field layouts now get icon tooltips immediately, the events bubble up in the dom.
