### ISSUE TITLE
Support for ACF PRO

### ISSUE THREAD

**Issue by 7immy** [urre/acf-fold-flexible#5]
This doesn't seem to work with ACF pro. Would be nice to see some support for it :)

**Comment by urre** [comment]
@7immy hi, this should work on ACF PRO. What issues do you have? What version?

**Comment by 7immy** [comment]
My bad, I didn't follow the instructions to rename the folder:
"Rename the folder from acf-fold-flexible-content-master to acf-fold-flexible-content"
Cheers @urre

**Comment by urre** [comment]
ok! you can install it here aswell: http://wordpress.org/plugins/acf-fold-flexible-content/
