### ISSUE TITLE
Can't toggle fields with the arrow icon

### ISSUE THREAD

**Issue by breadadams** [urre/acf-fold-flexible#7]
Hey! Awesome plugin, however I noticed that if you click directly on the arrow icon, the field doesn't toggle (although the icon does).

I've recorded an example:
https://www.dropbox.com/s/rnfvnx8uehsqz48/acf_fold_flex_bug.mov?dl=0

**Comment by urre** [comment]
thanks @breadadams, i will look into this

**Comment by urre** [comment]
@breadadams this should be solved now in 1.2.0

https://wordpress.org/support/plugin/acf-fold-flexible-content

**Comment by breadadams** [comment]
Awesome! Working great :smile:

**Comment by urre** [comment]
@breadadams :+1:
