### ISSUE TITLE
Icons "not working"?

### ISSUE THREAD

**Issue by breadadams** [urre/acf-fold-flexible#8]
Hey! Seems to be an issue with the icons on the foldable fields in the latest versions of your plugin + ACF Pro.

They're **all** showing _by default_, and on toggling a field they all disappear.

Uploaded a video here: http://quick.as/22jzcpej2

Advanced Custom Fields PRO v5.3.10
ACF Fold Flexible Content v1.3.1

**Comment by urre** [comment]
@breadadams hey! yes, unfortunately it does not work with the PRO version using the latest version. Working on a fix for this, hope i can get it out soon!

**Comment by breadadams** [comment]
Aha great @urre, look forward to the update 😄

**Comment by urre** [comment]
@breadadams Hi! New version 1.4.0 out, can you check if this works for you?
https://wordpress.org/plugins/acf-fold-flexible-content/changelog/

**Comment by breadadams** [comment]
Hey @urre , just updated to latest version but still doesn't seem to be working.

I don't see any icons at all on the flexible layout sections, and I'm seeing the following error in console: `http://mydomain.dev/wp-content/plugins/acf-fold-flexible-content/js/acf-fold-flexible.admin.pro.js?ver=4.6.1 `

**Advanced Custom Fields PRO v5.4.6
ACF Fold Flexible Content v1.4.0**

**Comment by urre** [comment]
@breadadams hm, should work. Can you paste your error message again?

**Comment by breadadams** [comment]
@urre I don't think the latest version from gh is pushed to the wp directory?

![image](https://cloud.githubusercontent.com/assets/5795227/19050629/c01d59a2-89af-11e6-8915-519d325f48bd.png)

Version is 1.4.0, but the `acf-fold-flexible.admin.pro.js` file is missing. I've tried deleting plugin and reinstalling and same files.

Just downloaded that file from repo and added in manually and working fine!

**Comment by breadadams** [comment]
Just got 1.4.1 update, installed and the pro js file is there now.

**Comment by urre** [comment]
@breadadams aahh, you're right! Thanks so much for pointing this out. The pro js file was missing in the svn repo, but is fixed now.

Can you check 1.4.1 if that works for you now!
https://wordpress.org/plugins/acf-fold-flexible-content/changelog/

**Comment by urre** [comment]
@breadadams thanks! 👍
